name: introduction_example
description: Demo app of the introduction_screen package
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^8.5.0

  introduction_screen:
    path: ../

flutter:
  uses-material-design: true

  assets:
    - assets/