name: introduction_screen
description: Introduction/Onboarding package for flutter app with some customizations possibilities
version: 1.0.7
author: Jean-Charles Moussé <jeancharles.msse@gmail.com>
homepage: https://github.com/pyozer/introduction_screen

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  dots_indicator: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: 'icon/asesorate.png'
  android: true
  ios: true                            

flutter:  
  fonts:
      - family: OpenSansBold
        fonts:
          - asset: fonts/OpenSans-Bold.ttf
      - family: OpenSansRegular
        fonts:
          - asset: fonts/OpenSans-Regular.ttf



